#! /bin/bash
octave_deps=(
    'autoconf'
    'automake'
    'bison'
    'default-jdk'
    'default-jdk-headless'
    'epstool'
    'flex'
    'fontconfig'
    'g++'
    'gcc'
    'gfortran'
    'gnuplot'
    'gnuplot-x11'
    'gperf'
    'gzip'
    'hdf5-helpers'
    'icoutils'
    'javahelper'
    'libaec-dev'
    'libarpack2-dev'
    'libblas-dev'
    'libbtf1.2.1'
    'libcsparse3.1.4'
    'libcurl4-gnutls-dev'
    'libexif-dev'
    'libfftw3-dev'
    'libflac-dev'
    'libfltk-cairo1.3'
    'libfltk-forms1.3'
    'libfltk-images1.3'
    'libfltk1.3-dev'
    'libfontconfig1-dev'
    'libfreetype6-dev'
    'libftgl-dev'
    'libftgl2'
    'libgl1-mesa-dev'
    'libgl2ps-dev'
    'libglpk-dev'
    'libgraphicsmagick++1-dev'
    'libgraphicsmagick1-dev'
    'libhdf5-cpp-11'
    'libhdf5-dev'
    'libhdf5-serial-dev'
    'libjack-dev'
    'libjasper-dev'
    'libklu1.3.3'
    'liblapack-dev'
    'libldl2.2.1'
    'libogg-dev'
    'libosmesa6-dev'
    'libpcre3-dev'
    'libportaudiocpp0'
    'libqhull-dev'
    'libqrupdate-dev'
    'libqscintilla2-dev'
    'libqt4-designer'
    'libqt4-dev'
    'libqt4-dev-bin'
    'libqt4-help'
    'libqt4-network'
    'libqt4-opengl-dev'
    'libqt4-qt3support'
    'libqt4-scripttools'
    'libqt4-svg'
    'libqt4-test'
    'libqtcore4'
    'libqtgui4'
    'libqtwebkit4'
    'libreadline-dev'
    'librsvg2-bin'
    'librsvg2-dev'
    'libsndfile1-dev'
    'libspqr2.0.2'
    'libsuitesparse-dev'
    'libtool'
    'libvorbis-dev'
    'libwmf-dev'
    'libxft-dev'
    'llvm-3.5-dev'
    'llvm-dev'
    'lpr'
    'make'
    'openjdk-8-jdk'
    'openjdk-8-jdk-headless'
    'perl'
    'portaudio19-dev'
    'pstoedit'
    'qt4-linguist-tools'
    'qt4-qmake'
    'rsync'
    'tar'
    'texinfo'
    'texlive'
    'transfig'
    'uuid-dev'
    'zlib1g-dev'
    )
len=${#octave_deps[@]}
echo "Running apt update"
sudo apt update > /dev/null
for i in "${!octave_deps[@]}"
do 
    pkg=${octave_deps[$i]}
    printf "%02d/%s Installing: %s\n" "$((i+1))" "$len" "$pkg"
    sudo -H apt install -y $pkg > /dev/null
done
echo "Done installing dependencies."
echo "To install Octave:" 
echo "1) Download the latest source .tar.gz file from the GNU Octave site."
echo "2) Extract the tarfile and cd into the directory from the terminal."
echo "3) Run the following commands, one at a time."
echo "    ./configure"
echo "    make -j8"
echo "    sudo make install"
echo "FINISHED"
echo "======================================================================="
